### ISSUE TITLE
Spelling mistake in "en/reason/index.html"

### ISSUE THREAD

**Issue by kapitonas** [sisimai/sisimai.github.io#47]
Description of ```Not Accept``` bounce resons have spelling mistake. ```Destinaion does not accept any message``` should be changed to ```Destination does *```

**Comment by azumakuniyuki** [comment]
@kapitonas I've fixed the issue, thanks :-)

**Comment by kapitonas** [comment]
No problem. Studding the application and how to use it. Probably will find some more little issues.
Also I have some questions about the application, data structures and bounce email JSON responses.

Can I ask about those here or should I do it in private somehow?

**Comment by azumakuniyuki** [comment]
@kapitonas We have no private channel to support, sorry. If you have any question about bug, spec, or  data structure, please open an issue at p5-Sisimai or rb-Sisimai which you are using.

- https://github.com/sisimai/p5-Sisimai/issues
- https://github.com/sisimai/rb-Sisimai/issues
